---
series: focal
bootstrap_mirror: http://archive.ubuntu.com/ubuntu/
system_mirror: https://fr.archive.ubuntu.com/ubuntu/
extra_packages:
  - apt-transport-https
  - ca-certificates
  - openssh-server
  - cloud-init
  - linux-virtual
files:
  '/etc/default/grub.d/50-cloudimg-settings.cfg': ./files/extra-grub-config.cfg
